version: "3.9"
services:
  webserver:
    container_name: PHP-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - 8001:80
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: password