#+title: BOHEMY
#+subtitle: Relazione Progetto Tecnologie Web
#+author: Osama Chelhaoui, Rupi Anton Ricardo, Bilal El Moutaren
#+date: 2023/2024
#+language: it
#+OPTIONS: toc
#+TOC: headlines 100


:TOC: headlines

* Componenti
 - Osama Chelhaoui 2042333
 - Bilal El Moutaren 2053470
 - Rupi Anton Ricardo 2054304

* Credenziali

| Tipo           | Username | Password |
|----------------+----------+----------|
| Amministratore | admin    | admin    |
| Utente         | user     | user     |

è possibile creare nuove credenziali all'interno del sito

* Referente

Il referente che ha effettuato il caricamento nella piattaforma Moodle (STEM): *Osama Chelhaoui*

Il referente che ha effettuato il caricamento nel Server: *Bilal El Moutaren*

* Link Sito

Il link per la correzione è: http://localhost:8080/... <-- da aggiungere

* Abstract
BOHEMY è un sito e-commerce nato in Antartide per la vendita di disegni in stile bohémien. Lo stile bohémien è un'espressione vibrante ed elettrica della creatività che abbraccia l'inconsueto. Non è vincolato da regole, spesso fonde diverse forme d'arte, culture e influenze storiche. È caratterizzato da ricchi motivi e colori vibranti, mescolando il naturale e il surreale. Per alcuni, esprime una celebrazione dell'individualità, della libertà e della gioia di creare senza confini. Per altri, è un'espressione di sperimentazione, esplorazione e di un'estetica personale del mondo.

Il codice è stato versionato tramite una repository GitHub, per permettere ai membri del gruppo di collaborare in maniera efficiente e produttiva, segnalare le problematiche e bug e mantenere sincronizzati i file del progetto. Inoltre, è stato utilizzato un container /Docker/, per permettere di sviluppare il progetto in maniera omogenea, come alternativa a /XAMPP/.

* Analisi dei requisiti
** Obbiettivi
L'obiettivo principale del sito è la vendita di stampe e quadri di opere d'arte in stile bohémien, uno stile sempre meno adottato con il passare degli anni. Il sito inoltre offre una dashboard per permettere all'amministratore di gestire le opere, facilitando di conseguenza la gestione complessiva del sito.
** Target
Il sito è stato sviluppato con attenzione per soddisfare di un pubblico ampio e diversificato. Rivolto principalmente agli adulti e giovani adulti, il sito offre un'ampia varietà di opere d'arte da poter collezionare. L'interfaccia utente è stata studiata per accogliere intuitivamente sia esperti che principianti, garantendo un'esperienza senza soluzione di continuità a chiunque desideri esplorare i contenuti del sito. Inoltre, il design responsivo del sito garantisce un'ottima esperienza su desktop, tablet, e smartphone.
* Progettazione e Sviluppo
** Architettura del sito
Il sito è strutturato con le seguenti pagine:
- Home: la pagina principale del sito; contiene un'introduzione sintetica e generale degli obbiettivi e servizi offerti dal sito;
- Collezione: mette in mostra la collezione completa dei disegni;
- Chi siamo: contiene le informazioni riguardanti l'impresa e una breve definizione dello stile bohémien;
- Contattaci: una pagina contenente le informazioni riguardanti il negozio fisico e un modulo per contattare in modo diretto l'impresa;
- Carrello: consente di salvare prodotti per poi acquistarli;
- Pagina del singolo prodotto: contiene le informazioni riguardanti il prodotto, come la descrizione e il prezzo;
- FAQ: contiene una varietà di domande che un visitatore potrebbe chiedersi;
- Informativa privacy: informa i regolamenti e le varie dichiarazioni privacy per la protezione dell'utente.
** Area privata
L'area privata è stata gestita dalle seguenti pagine
- Pagina di login: la pagina dove l'utente può accedere al sito per poter acquistare le stampe e i quadri, oltre a gestire le informazioni personali;
- Pagina di registrazione: la pagina dove l'utente può registrarsi per effettuare le operazioni sensitive, come procedere con l'acquisto delle stampe;
- Pagina dell'account: la pagina dove è possibile gestire le informazioni relative all'utente, offrendo la possibilità di modificare username, email, password ed eliminare completamente l'account.
- Pagina dell'amministratore: la pagina dove è possibile gestire le stampe da vendere.
** Suddivisione del lavoro
Il sito è stato progettato per essere sviluppato da tre persone, organizzando il carico di lavoro nel seguente modo:
- Osama Chelhaoui
  - Progettazione e sviluppo del codice /HTML/;
  - Progettazione e sviluppo del codice /CSS/;
  - Gestione dell'ambiente di sviluppo;
  - Validazione del sito e test dell'accessibilità;
  - Stesura e verifica della relazione.
- Bilal El Moutaren
  - Progettazione e sviluppo codice /PHP/;
  - Validazione dell'usabilità del sito;
  - Stesura e validazione del sito.
- Rupi Anton Ricardo
  - Progettazione e implementazione del database;
  - Redazione del contenuto web;
  - Sviluppo validazione di input front-end in Javascript;
  - Stesura e verifica della relazione.
** Front-End
*** HTML
Per definire la struttura e il contenuto del sito web è stato utilizzato /HTML5/. Per creare una struttura chiaramente definita e semplice da navigare per gli utenti, sono state seguite diverse regole. In particolare:
- Ci siamo assicurati di usare tag adeguati in ogni contesto per migliorare la comprensione per gli screen reader;
- Abbiamo mantenuto la separazione tra struttura, contenuto e comportamento, evitando di implementare codice js o fogli di stile all'interno dei file html;
- Per migliorare l'accessibilità del sito nei browser abbiamo implementato metatag e ciò di conseguenza aiuta ad ottenere un ranking migliore nei motori di ricerca.
Si è cercato di creare un file per i componenti principali del sito web, definendoli all'interno di tag ~<main>~, evitando di azzerare la struttura partendo dal tag ~<html>~, per migliorare l'organizzazione interna, ridurre il peso del sito invocando i componenti necessari in un contesto definito e minimizzare in generale i tempi di attesa.
*** CSS
La presentazione del sito è stata realizzata tramite la versione 3 di /CSS/. è stato realizzato un file ~style.css~ e una versione compressa per rendere più piccola la dimensione del file iniziale. è stato fatto uso ragionevole di di layout flex e grid, variabili e selettori in modo ragionevole per facilitare la progettazione. Abbiamo utilizzato la strategia Responsive Web Design che si basa sull'utilizzo di media-query per adattare il layout del sito web nei dispositivi mobili in base a dimensioni di viewport
*** JavaScript
Per gestire il comportamento del sito web, è stato fatto uso di alcuni file javascript: ~app.js~ e ~validate.js~. ~app.js~ è stato realizzato per gestire principalmente gli elementi del sito, tramite l'uso di listener, come ad esempio l'apertura del menu della navbar al click nel menù ad hamburger per i dispositivi mobili, la gestione del carosello per le recensioni o per aggiornare i costi all'interno del carrello. l'intenzione del gruppo era quella di aggiungere anche una barra di navigazione e gestire da javascript, ma a causa  della dimensione del gruppo e del tempo a disposizione non siamo stati in grado di farlo. Il secondo file (~validate.js~) è stato realizzato per gestire gli input all'interno dei vari form presenti all'interno del sito, per evitare di inserire dati scorretti, non adatti per il database e per migliorare l'esperienza dell'utente.
** Back-End
*** Database
La gestione dei dati del sito web si basa su un database SQL relazionale. Il database è composto dalle seguenti tabelle:
- Utente: contiene le informazioni relative al cliente, come ~username~, ~password~ ed ~email~;
- Disegni: permette di salvare le informazioni relative ai disegni che si intende vendere. Consente di salvare il ~titolo~ dell'opera, ~descrizione~, ~prezzo~, ~quantità~ di stampe disponibili, ~autore~ e un'anteprima della stampa in questione, in particolare vengono salvate le path delle posizioni delle immagini nei server. Le opere non devono avere lo stesso nome;
- Acquisti: è la relazione tra Utente e Disegni. Contiene ~IDacquisto~ e ~dataAcquisto~;
- Admin: contiene ~username~ e ~password~ e permette di effettuare il login all'interno del sito come amministratore.
                                 [[./database.svg]]
*** Sample dati
Per testare il database è stato generato un sample di dati per verificare il funzionamento, identificare le problematiche e monitorare le performance. I dati sono inclusi nel file sql all'interno del progetto.
*** PHP
Per quanto riguarda PHP è stata rispettata la completa separazione tra HTML e PHP. 
Questo ci permette di avere un codice più pulito e facilitare la manutenzione. 
Per generare le pagine dinamiche si è deciso di usare la funzione di rimpiazzo delle stringhe /str_replace()/, usate come placeholder nel file HTML template.
Di conseguenza viene caricata la pagina in una variabile, vengono processati i vari dati e infine rimpiazzati nella pagina inviandola al browser.
**** Connessione al database
Per quanto riguarda la connessione al database, è stata creata una classe statica chimata /db/ che gestisce i vari parametri di connessione ed effettua query. 
Le query sono parametrizzate, così da evitare il problema del sql injection. Inoltre è stato creato un file per ogni tabella inclusa nel database; 
ogni file gestisce la sua tabella tramite funzioni che a loro volta richiamano la classe /db/ ed effettuano query di selezione o modifica.
**** Autenticazione
Per quanto riguarda il sistema di autenticazione, è stato gestito tramite l'uso di sessioni (/PHP_SESSION/).
Quando un utente effettua l'accesso, nella sessione viene salvato il suo /username/, viene inoltre fatto il controllo per vedere se l'utente è un amministratore.
Per le sezioni di amministrazione del sito web viene fatto un ulteriore controllo per negare l'accesso al utente non amministratore. Per verificare effettivamente se 
l'utente è presente nel database, vengono effettuate query che controllano /username/ e /email/ assieme alla /password/ fornita nel form.
Per chiudere la sessione serve effettuare il logout che è gestito tramite le funzioni di PHP /session_destroy()/ e /session_abort()/
**** Gestion carrello
Nel sito è presente un carrello. Questo carrello viene gestito come una variabile /array/ di sessione tramite /PHP_SESSION/. Questa variabile è accessibile anche quando non si è fatto l'accesso
e permette di salvare i quadri per un possibile acquisto. Una volta che l'utente aggiunge al carello un quadro, viene aggiornato l'array e di conseguenza il carrello.
**** Gestione input
I form presenti nel sito dispongono dei controlli fatti da parte del server. Per verificare email e username sono stati utilizzate espressioni regolari.
Per comunicare errori nell'input si è fatto uso di una variabile di sessione con /PHP_SESSION/ che verrà rimpiazzata appositamente nella pagina.
**** Sicurezza
Per quanto riguarda la sicurezza del sito web sono state implementate le seguenti:
- vengono effettuate solo query parametriche tramite la funzione /prepare()/ di mysqli, questo previene gli attacchi come SQL injection
- l'utente base non può accedere alle sezioni del sito web dedicate all'amministratore grazie ai diversi controlli
** User Interface (UI)
Abbiamo cercato di seguire un layout di navigazione statico per consentire al visitatore, utente o amministratore del sito di mantenere il contesto e la prospettiva del loro percorso di navigazione, anche mentre esplorano contenuti diversi. Questa struttura è particolarmente adatta per tale tipologia di sito perché rende consistente e coerente l'interfaccia utente su diverse dimensioni di schermo.
Si è cercato di usare una varietà di font da applicare separatamente per intestazioni e pulsanti: [[https://www.fontshare.com/fonts/stardom][Stardom]], [[https://www.fontshare.com/fonts/gambarino][Gambarino]] e [[https://www.fontshare.com/fonts/author][Author]]. Stardom è un font display, adatto per i titoli e altri testi grandi per distinguerli dal resto del contenuto. Author è un font sans-serif, tipico per i testi che devono essere necessariamente e chiaramente leggibili (nel nostro caso per pulsanti ed etichette), famoso per il suo stile semplice e pulito, senza allungamenti alle estremità delle lettere. Gambarino è invece un font serif che abbiamo usato per il resto del contenuto del sito. Per garantire la compatibilità con tutti i browser abbiamo deciso di implementare diversi formati per ogni font. I formati più noti, che abbiamo di usare, sono:
- /WOFF2/: è il formato più recente e offre prestazioni migliori grazie alla sua compressione avanzata. è supportato da tutti i browser moderni, eccetto Internet Explorer;
- /WOFF/: è un formato meno recente ma ancora ampiamente supportato dai browser, incluso Internet Explorer versione 9 e successive;
- /TTF/ (TrueType): questo formato è supportato da tutti i browser. Tuttavia, non è compresso come /WOFF2/ e /WOFF/, quindi la dimensione potrebbe essere maggiore.
La dimensione della cartella infatti, dopo aver implementato i formati necessari, è di circa /857 KB/. è possibile implementare solamente /WOFF2/ e /WOFF/, ma si è deciso di implementare anche il formato TTF per supportare tutti i browser.
I colori sono stati scelti con particolare attenzione al contrasto per renderlo il più leggibile possibile alle persone soggette da disabilità. Per individuare il nome adeguato per ogni colore scelto, abbiamo fatto affidamento al tool offerto da [[https://chir.ag/projects/name-that-color/#4C4F56][chir.ag]], ottenendo i seguenti colori:
- ~orchid-white: #FFFDF2~;
- ~thunderbird: #D32D1F~;
- ~old-lace: #FDF5DF~;
Alcune immagini sono state convertite nel formato /WebP/, che combina la compressione con perdita di dati di /JPEG/, la compressione senza perdita di dati di /PNG/ e la capacità di animazione di /GIF/ per creare un formato di immagine flessibile. Ciò ci permette di risparmiare 25-34% di spazio rispetto a un'immagine /JPEG/ di qualità equivalente. Tuttavia, non tutti i browser supportano /WebP/, perciò sarebbe necessario implementare immagini di fallback in altri formati. Il nostro gruppo ha deciso di non aggiungere immagini di fallback e convertire solo alcune immagini in /WebP/.
** User Experience (UX)
Per testare, valutare e migliorare l'esperienza utente, si è fatto uso di strumenti di validazione, oltre alla partecipazione di una varietà di persone per valutare l'usabilità e il comfort nella navigazione. Per migliorare ulteriormente la UX, abbiamo lavorato per ridurre i tempi di attesa con una attenta progettazione, ci siamo assicurati che il sito operi correttamente su una varietà di dispositivi, risoluzioni e schermi, abbiamo reso la navigazione intuitiva, permettendo all'utente di trovare facilmente ciò che gli interessa, abbiamo reso il sito web accessibile a tutti gli utenti, inclusi coloro con disabilità. Ciò include l'uso di alternative testuali per le immagini, contrasto sufficiente per i colori e rendere il sito navigabile da tastiera. Inoltre abbiamo fatto in modo che il sito spieghi chiaramente il suo scopo nella pagina principale, indicando i servizi offerti e abbiamo incluso un'area in cui il visitatore può contattare il responsabile del sito web per fornire feedback e aiutare ad identificare le aree da migliorare.
* Test e Valutazione
Per ottenere un sito web accessibile e aderente agli standard più noti, tutte le pagine devono essere corrette e che facciano quanto dichiarato. Per fare ciò è stato fatto uso di diversi strumenti di validazione. I test sono stati effettuati su una varietà di dispositivi per assicurarci della compatibilità e delle performance ottimali. Il testing include:
- iPhone con iOS 16 e 17, usando Safari e Chrome;
- iPad con iPadOS 16 e 17, usando Safari e Chrome;
- dispositivi Android con Android 13 e 14, usando Chrome, Brave, Opera e Firefox;
- MacBook Pro con macOS 14.3, usando Chrome, Brave, Arc e Firefox;
- dispositivi Windows 11, laptop e desktop, usando Chrome, Brave, Opera e Firefox;
- dispositivi Linux (Ubuntu e Arch Linux), laptop e desktop, usando Brave e Firefox.
Per la convalidazione sono stati utilizzati i seguenti strumenti:
- Total Validator Basic (HTML): è uno strumento di validazione utilizzato per verificare l'accessibilità, la compatibilità con i browser, la conformità di /HTML/ e /CSS/ e per trovare link interrotti.
- W3C Markup Validation (HTML): uno strumento gratuito offerto dal World Wide Web Consortium (W3C) che permette di controllare la conformità dei documenti /HTML/ e /XHTML/;
- W3C CSS Validation (CSS): uno strumento sempre offerto da W3C per verificare la conformità dei file /CSS/
- Lighthouse. uno strumento open-source realizzato da Google, usato per migliorare la qualità delle pagine web. Lo strumento fornisce un set di audit per verificare l'accessibilità, la performance e le pratiche progressive web app (PWA) e SEO. Lighthouse può essere eseguito da un browser chromium, da riga di comando o come un modulo Node.js. Una volta completati gli audit, vengono generati dei rapporti sulla pagina web realizzata, con punteggi per ogni categoria e suggerimenti su come migliorarla.
* Accessibilità
Nel contesto dell'accessibilità, il gruppo si è basato sui principi dell'accessibilità definiti da /WCAG/: Percepibile, Operabile, Comprensibile e Robusto.
** Percepibile
Sono state implementate alternative testuali per vari tipi di media in modo da essere correttamente leggibili dagli screen reader. Dopo una attenta fase di progettazione, l'interfaccia utente è in grado di rispondere ed adattarsi ad un'ampia varietà di dispositivi mobili, attraverso l'utilizzo di misure relative e o in percentuale.
** Operabile
Sono stati aggiunti attributi adatti ai tag HTML per rendere accessibile e navigabile il sito web completamente da tastiera.
** Comprensibile
Dopo un attento studio, è stato scelto uno schema di colori con contrasti elevati, per facilitare la lettura per le persone che soffrono di disturbi visivi, rispettando il livello di accessibilità AA di *WCAG*. Inoltre sono stati stilati i link per renderli facilmente distinguibili all'interno del sito con una sottile sottolineatura. Per assistere l'utente all'inserimento, sono stati aggiunti suggerimenti, placeholder, etichette e auto completamenti nei form per guidare l'utente ad inserire dati corretti e migliorare in generale l'esperienza dell'utente.
** Robusto
Il sito è stato progettato per essere compatibile con diversi browser, tecnologie di assistenza e altri user agent, assicurando che i file siano validi e fornendo nomi e valori adatti.
* Conclusione
In conclusione, il processo di sviluppo e design del sito web per la vendita di stampre di stile bohémien è stata una esperienza impegnativa ma gratificante. Attraverso questo progetto abbiamo ottenuto una comprensione più profonda della progettazione web e dell'importanza dell'esperienza utente e dell'accessibilità. Il prodotto finale è un sito visivamente attraente facile da naviagree offre un'esperienza di acquisto per gli utenti senza soluzione di continuità. Inoltre si adatta in modo efficace per una varietà di dispositivi e schermi. Mentre c'erano sfide durante lo sviluppo, come assicurarsi che il sito sia compatibile su più browser e l'individuazione degli errori, questi ostacoli ci hanno fornito un'opportunità per l'apprendimento di questa tipologia di sviluppo e nuove tecniche di problem solving.
